### ISSUE TITLE
Czysty PHP

### ISSUE THREAD

**Issue by MESWEB** [ernestwisniewski/kbin#1]
WItam. Jestem zainteresowany projektem i moge pomoc troche. Chcialbym aby ten projekt byl w czystym PHP bez zadnych frameworkow. Czy istnieje cien szansy nad stworzeniem tego projektu?

**Comment by piotrfilipek** [comment]
Wątpię w to. Przecież pisanie złożonej aplikacji bez jakiegokolwiek frameworka to jest katorga.

**Comment by ernestwisniewski** [comment]
@piotrfilipek zgadza się, niemniej po fazie wesołego prototypowania przyjdzie czas na refaktor i rozpisanie jakiejś sensownej architektury ;-)

**Comment by MESWEB** [comment]
@piotrfilipek @ernestwisniewski Mysle ze nie macie zbytnio wiedzy o czystym PHP. Najgorsze jak juz bedziecie chcieli cos zmodyfikowac wtedy bedziecie przerabiac frameworka?

**Comment by ernestwisniewski** [comment]
@MESWEB rozumiem zalety użycia czystego PHP i jestem zwolennikiem podejścia framework-agnostic. Tu jednak potrzebuję narzędzi do szybkiego prototypowania, chcę szybko sprawdzić jak pomysły sprawdzają się w praktyce. Dalsze etapy będą dążyły do refaktoru kodu, lecz narazie czas, który mogę poświęcić na ten projekt jest bardzo ograniczony.
